---
- name: Check if machine is joined to AD domain
  hosts: all
  gather_facts: no
  become: true
  
  tasks:
    - name: Gather OS version and distribution facts
      debug:
        var: ansible_distribution_version
      register: os_version
