---
- name: Configure Samba and Winbind on Solaris
  hosts: all
  become: yes
  tasks:
    - name: Check if the server is joined to the domain
      command: net ads testjoin
      register: domain_join_status
      ignore_errors: yes

    - name: Determine if the server is already joined to the domain
      set_fact:
        already_joined: "{{ 'Join is OK' in domain_join_status.stdout }}"

    - name: Print message if server is already joined
      debug:
        msg: "Server is already joined to the domain."
      when: already_joined

    - name: Stop playbook execution if server is already joined
      meta: end_play
      when: already_joined
