---
- name: Detect and Execute OS-specific tasks
  hosts: "{{ host_list }}"
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
    username_var: "{{ username | default('') }}"
    groupname_var: "{{ groupname | default('') }}"
  tasks:
  - name: Execute command for user
    shell: realm permit {{ username_var }}
    when: username_var != ''
    register: command_output
  - name: Execute command for group
    shell: realm permit -g {{ groupname_var }}
    when: groupname_var != ''
    register: command_output
