---
- name: Detect and Execute OS-specific tasks
  hosts: "{{ host_list }}"
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
    whitelist_users: "{{ whitelist_users_awx | default('') }}"
    whitelist_groups: "{{ whitelist_groups_awx| default('') }}"    
  tasks:
  - name: Execute command for user
    shell: realm permit {{ whitelist_users }}
    when: username_var != ''
    register: command_output
  - name: Execute command for group
    shell: realm permit -g {{ whitelist_groups }}
    when: groupname_var != ''
    register: command_output
